// Mocks generated by Mockito 5.0.15 from annotations
// in basf_dashboard/test/app/modules/currency/infra/repositories/get-currency-by-type.repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:basf_dashboard/app/modules/currency/domain/enums/currency-type.enum.dart'
    as _i5;
import 'package:basf_dashboard/app/modules/currency/infra/data/datasouce/get-currency-by-type.datasource.dart'
    as _i3;
import 'package:basf_dashboard/app/modules/currency/infra/models/currency.model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

class _FakeCurrencyModel_0 extends _i1.Fake implements _i2.CurrencyModel {}

/// A class which mocks [GetCurrencyByTypeDatasouce].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetCurrencyByTypeDatasouce extends _i1.Mock
    implements _i3.GetCurrencyByTypeDatasouce {
  MockGetCurrencyByTypeDatasouce() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.CurrencyModel> getCurrency(_i5.CurrencyType? currencyType) =>
      (super.noSuchMethod(Invocation.method(#getCurrency, [currencyType]),
              returnValue:
                  Future<_i2.CurrencyModel>.value(_FakeCurrencyModel_0()))
          as _i4.Future<_i2.CurrencyModel>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [CurrencyModel].
///
/// See the documentation for Mockito's code generation for more information.
class MockCurrencyModel extends _i1.Mock implements _i2.CurrencyModel {
  MockCurrencyModel() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get code =>
      (super.noSuchMethod(Invocation.getter(#code), returnValue: '') as String);
  @override
  set code(String? _code) => super.noSuchMethod(Invocation.setter(#code, _code),
      returnValueForMissingStub: null);
  @override
  String get codein =>
      (super.noSuchMethod(Invocation.getter(#codein), returnValue: '')
          as String);
  @override
  set codein(String? _codein) =>
      super.noSuchMethod(Invocation.setter(#codein, _codein),
          returnValueForMissingStub: null);
  @override
  String get high =>
      (super.noSuchMethod(Invocation.getter(#high), returnValue: '') as String);
  @override
  set high(String? _high) => super.noSuchMethod(Invocation.setter(#high, _high),
      returnValueForMissingStub: null);
  @override
  String get low =>
      (super.noSuchMethod(Invocation.getter(#low), returnValue: '') as String);
  @override
  set low(String? _low) => super.noSuchMethod(Invocation.setter(#low, _low),
      returnValueForMissingStub: null);
  @override
  Map<String, dynamic> toMap() =>
      (super.noSuchMethod(Invocation.method(#toMap, []),
          returnValue: <String, dynamic>{}) as Map<String, dynamic>);
  @override
  String toJson() =>
      (super.noSuchMethod(Invocation.method(#toJson, []), returnValue: '')
          as String);
  @override
  String toString() => super.toString();
}
